/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApproachVsBuildFromScratchRouteImport } from './routes/approach_.vs-build-from-scratch'
import { Route as ApproachVsConsultantsRouteImport } from './routes/approach_.vs-consultants'
import { Route as ApproachVsFreelancersRouteImport } from './routes/approach_.vs-freelancers'
import { Route as ApproachVsHiringRouteImport } from './routes/approach_.vs-hiring'
import { Route as ApproachVsItServicesRouteImport } from './routes/approach_.vs-it-services'
import { Route as ApproachVsStaffingRouteImport } from './routes/approach_.vs-staffing'
import { Route as WorkCapitalEquipmentRouteImport } from './routes/work_.capital-equipment'
import { Route as WorkDemandForecastingRouteImport } from './routes/work_.demand-forecasting'
import { Route as WorkEcommerceReportingRouteImport } from './routes/work_.ecommerce-reporting'
import { Route as WorkEducationBiRouteImport } from './routes/work_.education-bi'
import { Route as WorkEnergyAuditRouteImport } from './routes/work_.energy-audit'
import { Route as WorkErpGlobalManufacturingRouteImport } from './routes/work_.erp-global-manufacturing'
import { Route as WorkEvBatteryRouteImport } from './routes/work_.ev-battery'
import { Route as WorkEvCabSchedulingRouteImport } from './routes/work_.ev-cab-scheduling'
import { Route as WorkFmcgFieldSalesRouteImport } from './routes/work_.fmcg-field-sales'
import { Route as WorkHeritageMappingRouteImport } from './routes/work_.heritage-mapping'
import { Route as WorkPharmaFieldForceRouteImport } from './routes/work_.pharma-field-force'
import { Route as WorkRetailManufacturingRouteImport } from './routes/work_.retail-manufacturing'
import { Route as WorkSolarBiRouteImport } from './routes/work_.solar-bi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachVsBuildFromScratchRoute =
  ApproachVsBuildFromScratchRouteImport.update({
    id: '/approach_/vs-build-from-scratch',
    path: '/approach/vs-build-from-scratch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApproachVsConsultantsRoute = ApproachVsConsultantsRouteImport.update({
  id: '/approach_/vs-consultants',
  path: '/approach/vs-consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachVsFreelancersRoute = ApproachVsFreelancersRouteImport.update({
  id: '/approach_/vs-freelancers',
  path: '/approach/vs-freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachVsHiringRoute = ApproachVsHiringRouteImport.update({
  id: '/approach_/vs-hiring',
  path: '/approach/vs-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachVsItServicesRoute = ApproachVsItServicesRouteImport.update({
  id: '/approach_/vs-it-services',
  path: '/approach/vs-it-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachVsStaffingRoute = ApproachVsStaffingRouteImport.update({
  id: '/approach_/vs-staffing',
  path: '/approach/vs-staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCapitalEquipmentRoute = WorkCapitalEquipmentRouteImport.update({
  id: '/work_/capital-equipment',
  path: '/work/capital-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDemandForecastingRoute = WorkDemandForecastingRouteImport.update({
  id: '/work_/demand-forecasting',
  path: '/work/demand-forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEcommerceReportingRoute = WorkEcommerceReportingRouteImport.update({
  id: '/work_/ecommerce-reporting',
  path: '/work/ecommerce-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEducationBiRoute = WorkEducationBiRouteImport.update({
  id: '/work_/education-bi',
  path: '/work/education-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEnergyAuditRoute = WorkEnergyAuditRouteImport.update({
  id: '/work_/energy-audit',
  path: '/work/energy-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkErpGlobalManufacturingRoute =
  WorkErpGlobalManufacturingRouteImport.update({
    id: '/work_/erp-global-manufacturing',
    path: '/work/erp-global-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkEvBatteryRoute = WorkEvBatteryRouteImport.update({
  id: '/work_/ev-battery',
  path: '/work/ev-battery',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEvCabSchedulingRoute = WorkEvCabSchedulingRouteImport.update({
  id: '/work_/ev-cab-scheduling',
  path: '/work/ev-cab-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFmcgFieldSalesRoute = WorkFmcgFieldSalesRouteImport.update({
  id: '/work_/fmcg-field-sales',
  path: '/work/fmcg-field-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkHeritageMappingRoute = WorkHeritageMappingRouteImport.update({
  id: '/work_/heritage-mapping',
  path: '/work/heritage-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPharmaFieldForceRoute = WorkPharmaFieldForceRouteImport.update({
  id: '/work_/pharma-field-force',
  path: '/work/pharma-field-force',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRetailManufacturingRoute = WorkRetailManufacturingRouteImport.update({
  id: '/work_/retail-manufacturing',
  path: '/work/retail-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSolarBiRoute = WorkSolarBiRouteImport.update({
  id: '/work_/solar-bi',
  path: '/work/solar-bi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/work': typeof WorkRoute
  '/approach/vs-build-from-scratch': typeof ApproachVsBuildFromScratchRoute
  '/approach/vs-consultants': typeof ApproachVsConsultantsRoute
  '/approach/vs-freelancers': typeof ApproachVsFreelancersRoute
  '/approach/vs-hiring': typeof ApproachVsHiringRoute
  '/approach/vs-it-services': typeof ApproachVsItServicesRoute
  '/approach/vs-staffing': typeof ApproachVsStaffingRoute
  '/work/capital-equipment': typeof WorkCapitalEquipmentRoute
  '/work/demand-forecasting': typeof WorkDemandForecastingRoute
  '/work/ecommerce-reporting': typeof WorkEcommerceReportingRoute
  '/work/education-bi': typeof WorkEducationBiRoute
  '/work/energy-audit': typeof WorkEnergyAuditRoute
  '/work/erp-global-manufacturing': typeof WorkErpGlobalManufacturingRoute
  '/work/ev-battery': typeof WorkEvBatteryRoute
  '/work/ev-cab-scheduling': typeof WorkEvCabSchedulingRoute
  '/work/fmcg-field-sales': typeof WorkFmcgFieldSalesRoute
  '/work/heritage-mapping': typeof WorkHeritageMappingRoute
  '/work/pharma-field-force': typeof WorkPharmaFieldForceRoute
  '/work/retail-manufacturing': typeof WorkRetailManufacturingRoute
  '/work/solar-bi': typeof WorkSolarBiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/work': typeof WorkRoute
  '/approach/vs-build-from-scratch': typeof ApproachVsBuildFromScratchRoute
  '/approach/vs-consultants': typeof ApproachVsConsultantsRoute
  '/approach/vs-freelancers': typeof ApproachVsFreelancersRoute
  '/approach/vs-hiring': typeof ApproachVsHiringRoute
  '/approach/vs-it-services': typeof ApproachVsItServicesRoute
  '/approach/vs-staffing': typeof ApproachVsStaffingRoute
  '/work/capital-equipment': typeof WorkCapitalEquipmentRoute
  '/work/demand-forecasting': typeof WorkDemandForecastingRoute
  '/work/ecommerce-reporting': typeof WorkEcommerceReportingRoute
  '/work/education-bi': typeof WorkEducationBiRoute
  '/work/energy-audit': typeof WorkEnergyAuditRoute
  '/work/erp-global-manufacturing': typeof WorkErpGlobalManufacturingRoute
  '/work/ev-battery': typeof WorkEvBatteryRoute
  '/work/ev-cab-scheduling': typeof WorkEvCabSchedulingRoute
  '/work/fmcg-field-sales': typeof WorkFmcgFieldSalesRoute
  '/work/heritage-mapping': typeof WorkHeritageMappingRoute
  '/work/pharma-field-force': typeof WorkPharmaFieldForceRoute
  '/work/retail-manufacturing': typeof WorkRetailManufacturingRoute
  '/work/solar-bi': typeof WorkSolarBiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/work': typeof WorkRoute
  '/approach_/vs-build-from-scratch': typeof ApproachVsBuildFromScratchRoute
  '/approach_/vs-consultants': typeof ApproachVsConsultantsRoute
  '/approach_/vs-freelancers': typeof ApproachVsFreelancersRoute
  '/approach_/vs-hiring': typeof ApproachVsHiringRoute
  '/approach_/vs-it-services': typeof ApproachVsItServicesRoute
  '/approach_/vs-staffing': typeof ApproachVsStaffingRoute
  '/work_/capital-equipment': typeof WorkCapitalEquipmentRoute
  '/work_/demand-forecasting': typeof WorkDemandForecastingRoute
  '/work_/ecommerce-reporting': typeof WorkEcommerceReportingRoute
  '/work_/education-bi': typeof WorkEducationBiRoute
  '/work_/energy-audit': typeof WorkEnergyAuditRoute
  '/work_/erp-global-manufacturing': typeof WorkErpGlobalManufacturingRoute
  '/work_/ev-battery': typeof WorkEvBatteryRoute
  '/work_/ev-cab-scheduling': typeof WorkEvCabSchedulingRoute
  '/work_/fmcg-field-sales': typeof WorkFmcgFieldSalesRoute
  '/work_/heritage-mapping': typeof WorkHeritageMappingRoute
  '/work_/pharma-field-force': typeof WorkPharmaFieldForceRoute
  '/work_/retail-manufacturing': typeof WorkRetailManufacturingRoute
  '/work_/solar-bi': typeof WorkSolarBiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/calculator'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/what-we-build'
    | '/work'
    | '/approach/vs-build-from-scratch'
    | '/approach/vs-consultants'
    | '/approach/vs-freelancers'
    | '/approach/vs-hiring'
    | '/approach/vs-it-services'
    | '/approach/vs-staffing'
    | '/work/capital-equipment'
    | '/work/demand-forecasting'
    | '/work/ecommerce-reporting'
    | '/work/education-bi'
    | '/work/energy-audit'
    | '/work/erp-global-manufacturing'
    | '/work/ev-battery'
    | '/work/ev-cab-scheduling'
    | '/work/fmcg-field-sales'
    | '/work/heritage-mapping'
    | '/work/pharma-field-force'
    | '/work/retail-manufacturing'
    | '/work/solar-bi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/calculator'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/what-we-build'
    | '/work'
    | '/approach/vs-build-from-scratch'
    | '/approach/vs-consultants'
    | '/approach/vs-freelancers'
    | '/approach/vs-hiring'
    | '/approach/vs-it-services'
    | '/approach/vs-staffing'
    | '/work/capital-equipment'
    | '/work/demand-forecasting'
    | '/work/ecommerce-reporting'
    | '/work/education-bi'
    | '/work/energy-audit'
    | '/work/erp-global-manufacturing'
    | '/work/ev-battery'
    | '/work/ev-cab-scheduling'
    | '/work/fmcg-field-sales'
    | '/work/heritage-mapping'
    | '/work/pharma-field-force'
    | '/work/retail-manufacturing'
    | '/work/solar-bi'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/calculator'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/what-we-build'
    | '/work'
    | '/approach_/vs-build-from-scratch'
    | '/approach_/vs-consultants'
    | '/approach_/vs-freelancers'
    | '/approach_/vs-hiring'
    | '/approach_/vs-it-services'
    | '/approach_/vs-staffing'
    | '/work_/capital-equipment'
    | '/work_/demand-forecasting'
    | '/work_/ecommerce-reporting'
    | '/work_/education-bi'
    | '/work_/energy-audit'
    | '/work_/erp-global-manufacturing'
    | '/work_/ev-battery'
    | '/work_/ev-cab-scheduling'
    | '/work_/fmcg-field-sales'
    | '/work_/heritage-mapping'
    | '/work_/pharma-field-force'
    | '/work_/retail-manufacturing'
    | '/work_/solar-bi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
  WorkRoute: typeof WorkRoute
  ApproachVsBuildFromScratchRoute: typeof ApproachVsBuildFromScratchRoute
  ApproachVsConsultantsRoute: typeof ApproachVsConsultantsRoute
  ApproachVsFreelancersRoute: typeof ApproachVsFreelancersRoute
  ApproachVsHiringRoute: typeof ApproachVsHiringRoute
  ApproachVsItServicesRoute: typeof ApproachVsItServicesRoute
  ApproachVsStaffingRoute: typeof ApproachVsStaffingRoute
  WorkCapitalEquipmentRoute: typeof WorkCapitalEquipmentRoute
  WorkDemandForecastingRoute: typeof WorkDemandForecastingRoute
  WorkEcommerceReportingRoute: typeof WorkEcommerceReportingRoute
  WorkEducationBiRoute: typeof WorkEducationBiRoute
  WorkEnergyAuditRoute: typeof WorkEnergyAuditRoute
  WorkErpGlobalManufacturingRoute: typeof WorkErpGlobalManufacturingRoute
  WorkEvBatteryRoute: typeof WorkEvBatteryRoute
  WorkEvCabSchedulingRoute: typeof WorkEvCabSchedulingRoute
  WorkFmcgFieldSalesRoute: typeof WorkFmcgFieldSalesRoute
  WorkHeritageMappingRoute: typeof WorkHeritageMappingRoute
  WorkPharmaFieldForceRoute: typeof WorkPharmaFieldForceRoute
  WorkRetailManufacturingRoute: typeof WorkRetailManufacturingRoute
  WorkSolarBiRoute: typeof WorkSolarBiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-build-from-scratch': {
      id: '/approach_/vs-build-from-scratch'
      path: '/approach/vs-build-from-scratch'
      fullPath: '/approach/vs-build-from-scratch'
      preLoaderRoute: typeof ApproachVsBuildFromScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-consultants': {
      id: '/approach_/vs-consultants'
      path: '/approach/vs-consultants'
      fullPath: '/approach/vs-consultants'
      preLoaderRoute: typeof ApproachVsConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-freelancers': {
      id: '/approach_/vs-freelancers'
      path: '/approach/vs-freelancers'
      fullPath: '/approach/vs-freelancers'
      preLoaderRoute: typeof ApproachVsFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-hiring': {
      id: '/approach_/vs-hiring'
      path: '/approach/vs-hiring'
      fullPath: '/approach/vs-hiring'
      preLoaderRoute: typeof ApproachVsHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-it-services': {
      id: '/approach_/vs-it-services'
      path: '/approach/vs-it-services'
      fullPath: '/approach/vs-it-services'
      preLoaderRoute: typeof ApproachVsItServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach_/vs-staffing': {
      id: '/approach_/vs-staffing'
      path: '/approach/vs-staffing'
      fullPath: '/approach/vs-staffing'
      preLoaderRoute: typeof ApproachVsStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/capital-equipment': {
      id: '/work_/capital-equipment'
      path: '/work/capital-equipment'
      fullPath: '/work/capital-equipment'
      preLoaderRoute: typeof WorkCapitalEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/demand-forecasting': {
      id: '/work_/demand-forecasting'
      path: '/work/demand-forecasting'
      fullPath: '/work/demand-forecasting'
      preLoaderRoute: typeof WorkDemandForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/ecommerce-reporting': {
      id: '/work_/ecommerce-reporting'
      path: '/work/ecommerce-reporting'
      fullPath: '/work/ecommerce-reporting'
      preLoaderRoute: typeof WorkEcommerceReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/education-bi': {
      id: '/work_/education-bi'
      path: '/work/education-bi'
      fullPath: '/work/education-bi'
      preLoaderRoute: typeof WorkEducationBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/energy-audit': {
      id: '/work_/energy-audit'
      path: '/work/energy-audit'
      fullPath: '/work/energy-audit'
      preLoaderRoute: typeof WorkEnergyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/erp-global-manufacturing': {
      id: '/work_/erp-global-manufacturing'
      path: '/work/erp-global-manufacturing'
      fullPath: '/work/erp-global-manufacturing'
      preLoaderRoute: typeof WorkErpGlobalManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/ev-battery': {
      id: '/work_/ev-battery'
      path: '/work/ev-battery'
      fullPath: '/work/ev-battery'
      preLoaderRoute: typeof WorkEvBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/ev-cab-scheduling': {
      id: '/work_/ev-cab-scheduling'
      path: '/work/ev-cab-scheduling'
      fullPath: '/work/ev-cab-scheduling'
      preLoaderRoute: typeof WorkEvCabSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/fmcg-field-sales': {
      id: '/work_/fmcg-field-sales'
      path: '/work/fmcg-field-sales'
      fullPath: '/work/fmcg-field-sales'
      preLoaderRoute: typeof WorkFmcgFieldSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/heritage-mapping': {
      id: '/work_/heritage-mapping'
      path: '/work/heritage-mapping'
      fullPath: '/work/heritage-mapping'
      preLoaderRoute: typeof WorkHeritageMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/pharma-field-force': {
      id: '/work_/pharma-field-force'
      path: '/work/pharma-field-force'
      fullPath: '/work/pharma-field-force'
      preLoaderRoute: typeof WorkPharmaFieldForceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/retail-manufacturing': {
      id: '/work_/retail-manufacturing'
      path: '/work/retail-manufacturing'
      fullPath: '/work/retail-manufacturing'
      preLoaderRoute: typeof WorkRetailManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/solar-bi': {
      id: '/work_/solar-bi'
      path: '/work/solar-bi'
      fullPath: '/work/solar-bi'
      preLoaderRoute: typeof WorkSolarBiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
  WorkRoute: WorkRoute,
  ApproachVsBuildFromScratchRoute: ApproachVsBuildFromScratchRoute,
  ApproachVsConsultantsRoute: ApproachVsConsultantsRoute,
  ApproachVsFreelancersRoute: ApproachVsFreelancersRoute,
  ApproachVsHiringRoute: ApproachVsHiringRoute,
  ApproachVsItServicesRoute: ApproachVsItServicesRoute,
  ApproachVsStaffingRoute: ApproachVsStaffingRoute,
  WorkCapitalEquipmentRoute: WorkCapitalEquipmentRoute,
  WorkDemandForecastingRoute: WorkDemandForecastingRoute,
  WorkEcommerceReportingRoute: WorkEcommerceReportingRoute,
  WorkEducationBiRoute: WorkEducationBiRoute,
  WorkEnergyAuditRoute: WorkEnergyAuditRoute,
  WorkErpGlobalManufacturingRoute: WorkErpGlobalManufacturingRoute,
  WorkEvBatteryRoute: WorkEvBatteryRoute,
  WorkEvCabSchedulingRoute: WorkEvCabSchedulingRoute,
  WorkFmcgFieldSalesRoute: WorkFmcgFieldSalesRoute,
  WorkHeritageMappingRoute: WorkHeritageMappingRoute,
  WorkPharmaFieldForceRoute: WorkPharmaFieldForceRoute,
  WorkRetailManufacturingRoute: WorkRetailManufacturingRoute,
  WorkSolarBiRoute: WorkSolarBiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
